### ISSUE TITLE
Updating to “go-outline@0.6.0” failed

### ISSUE THREAD

**Issue by maticmeznar** [frairon/go-outline#51]
I've been using Atom with go-outline@0.5.0 and when I try updating to 0.6.0, I get the following error log:

```
> runas@3.1.1 install /tmp/apm-install-dir-116730-6946-lo1sro/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116730-6946-lo1sro/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116730-6946-lo1sro/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas/build'

In file included from ../../nan/nan.h:2190:0,
                 from ../src/main.cc:1:
../../nan/nan_object_wrap.h:117:19: error: missing ')' after "defined"
../../nan/nan_object_wrap.h:117:0: error: unterminated #if
 #if defined(V8_MAJ
 ^
../../nan/nan_object_wrap.h:9:0: error: unterminated #ifndef
 #ifndef NAN_OBJECT_WRAP_H_
 ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h:2244:1: error: expected unqualified-id before ‘namespace’
 namespace imp {
 ^
In file included from ../../nan/nan.h:47:0,
                 from ../src/main.cc:1:
/home/matic/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:424:3: error: expected ‘}’ at end of input
   }
   ^
/home/matic/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:446:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)
   ^
../src/main.cc:76:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(runas, Init)
 ^
In file included from ../../nan/nan.h:2190:0,
                 from ../src/main.cc:1:
../../nan/nan_object_wrap.h: In member function ‘v8::Local<v8::Object> Nan::ObjectWrap::handle() const’:
../../nan/nan_object_wrap.h:43:16: error: ‘handle_’ was not declared in this scope
     return New(handle_);
                ^
../../nan/nan_object_wrap.h: In member function ‘Nan::Persistent<v8::Object>& Nan::ObjectWrap::persistent()’:
../../nan/nan_object_wrap.h:48:12: error: ‘handle_’ was not declared in this scope
     return handle_;
            ^
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:66:15: error: ‘WeakCallback’ was not declared in this scope
         this, WeakCallback, v8::WeakCallbackType::kParameter);
               ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:2227:3: error: expected unqualified-id at end of input
   }
   ^
../../nan/nan.h:2227:3: error: expected ‘}’ at end of input
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116730-6946-lo1sro/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/matic/.atom/.apm/.apmrc" "--userconfig" "/home/matic/.atom/.apmrc" "install" "/tmp/d-116730-6946-1ehjx2b/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116730-6946-lo1sro/npm-debug.log
```

**Comment by FryDay** [comment]
Similar issue:
```gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.11.2-1-ARCH
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jordan/.atom/packages/go-outline/node_modules/pathwatcher
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok ```

**Comment by frairon** [comment]
I removed pathwatcher, so this issue shouldn't occur anymore
