### ISSUE TITLE
windows 10(64bit) cannot install this plugin

### ISSUE THREAD

**Issue by zhiyuan1024** [frairon/go-outline#61]
The output is : 

> node-gyp rebuild
> C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i\node_modules\go-outline\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\zhiyu\AppData\Local\atom\app-1.21.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zhiyu\AppData\Local\atom\app-1.21.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
> �ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
> MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i\node_modules\go-outline\node_modules\runas\build\binding.sln]
> C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i
> `-- (empty)
> 
> 
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\zhiyu\AppData\Local\atom\app-1.21.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Users\\zhiyu\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\zhiyu\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i\node_modules\go-outline\node_modules\runas
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i\package.json'
> npm WARN apm-install-dir-117925-11504-x4e9t0.qocrs02j4i No description
> npm WARN apm-install-dir-117925-11504-x4e9t0.qocrs02j4i No repository field.
> npm WARN apm-install-dir-117925-11504-x4e9t0.qocrs02j4i No README data
> npm WARN apm-install-dir-117925-11504-x4e9t0.qocrs02j4i No license field.
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Users\\zhiyu\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\zhiyu\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\zhiyu\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\zhiyu\\.atom\\.apmrc" "install" "C:\\Users\\zhiyu\\AppData\\Local\\Temp\\d-117925-11504-c33our.zhtz1l9pb9\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! runas@3.1.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the runas package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs runas
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls runas
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\zhiyu\AppData\Local\Temp\apm-install-dir-117925-11504-x4e9t0.qocrs02j4i\npm-debug.log
> npm ERR! code 1

**Comment by ghost** [comment]
Same problem here
